window.esdocSearchIndex = [
  [
    "@osjs/gui/src/components/box.js~box",
    "function/index.html#static-function-Box",
    "<span>Box</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Box.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/boxcontainer.js~boxcontainer",
    "function/index.html#static-function-BoxContainer",
    "<span>BoxContainer</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/BoxContainer.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/boxstyled.js~boxstyled",
    "function/index.html#static-function-BoxStyled",
    "<span>BoxStyled</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/BoxStyled.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/button.js~button",
    "function/index.html#static-function-Button",
    "<span>Button</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Button.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/contextmenu.js~contextmenu",
    "class/src/contextmenu.js~ContextMenu.html",
    "<span>ContextMenu</span> <span class=\"search-result-import-path\">@osjs/gui/src/contextmenu.js</span>",
    "class"
  ],
  [
    "@osjs/gui/src/components/element.js~element",
    "function/index.html#static-function-Element",
    "<span>Element</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Element.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/expander.js~expander",
    "function/index.html#static-function-Expander",
    "<span>Expander</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Expander.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/provider.js~guiserviceprovider",
    "class/src/provider.js~GUIServiceProvider.html",
    "<span>GUIServiceProvider</span> <span class=\"search-result-import-path\">@osjs/gui/src/provider.js</span>",
    "class"
  ],
  [
    "@osjs/gui/src/components/icon.js~icon",
    "function/index.html#static-function-Icon",
    "<span>Icon</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Icon.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/iframe.js~iframe",
    "function/index.html#static-function-Iframe",
    "<span>Iframe</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Iframe.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/image.js~image",
    "function/index.html#static-function-Image",
    "<span>Image</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Image.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/label.js~label",
    "function/index.html#static-function-Label",
    "<span>Label</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Label.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/menu.js~menu",
    "function/index.html#static-function-Menu",
    "<span>Menu</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Menu.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/menubar.js~menubar",
    "function/index.html#static-function-Menubar",
    "<span>Menubar</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Menubar.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/menubar.js~menubaritem",
    "function/index.html#static-function-MenubarItem",
    "<span>MenubarItem</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Menubar.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/panes.js~panes",
    "function/index.html#static-function-Panes",
    "<span>Panes</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Panes.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/progressbar.js~progressbar",
    "function/index.html#static-function-Progressbar",
    "<span>Progressbar</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Progressbar.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/rangefield.js~rangefield",
    "function/index.html#static-function-RangeField",
    "<span>RangeField</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/RangeField.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/selectfield.js~selectfield",
    "function/index.html#static-function-SelectField",
    "<span>SelectField</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/SelectField.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/statusbar.js~statusbar",
    "function/index.html#static-function-Statusbar",
    "<span>Statusbar</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Statusbar.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/tabs.js~tabs",
    "function/index.html#static-function-Tabs",
    "<span>Tabs</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Tabs.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/textfield.js~textfield",
    "function/index.html#static-function-TextField",
    "<span>TextField</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/TextField.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/textareafield.js~textareafield",
    "function/index.html#static-function-TextareaField",
    "<span>TextareaField</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/TextareaField.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/togglefield.js~togglefield",
    "function/index.html#static-function-ToggleField",
    "<span>ToggleField</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/ToggleField.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/toolbar.js~toolbar",
    "function/index.html#static-function-Toolbar",
    "<span>Toolbar</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Toolbar.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/components/video.js~video",
    "function/index.html#static-function-Video",
    "<span>Video</span> <span class=\"search-result-import-path\">@osjs/gui/src/components/Video.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/element.js~createfield",
    "function/index.html#static-function-createField",
    "<span>createField</span> <span class=\"search-result-import-path\">@osjs/gui/src/element.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/utils.js~doubletap",
    "function/index.html#static-function-doubleTap",
    "<span>doubleTap</span> <span class=\"search-result-import-path\">@osjs/gui/src/utils.js</span>",
    "function"
  ],
  [
    "@osjs/gui/src/utils.js~filteredprops",
    "function/index.html#static-function-filteredProps",
    "<span>filteredProps</span> <span class=\"search-result-import-path\">@osjs/gui/src/utils.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/components/box.js",
    "file/src/components/Box.js.html",
    "src/components/Box.js",
    "file"
  ],
  [
    "src/components/boxcontainer.js",
    "file/src/components/BoxContainer.js.html",
    "src/components/BoxContainer.js",
    "file"
  ],
  [
    "src/components/boxstyled.js",
    "file/src/components/BoxStyled.js.html",
    "src/components/BoxStyled.js",
    "file"
  ],
  [
    "src/components/button.js",
    "file/src/components/Button.js.html",
    "src/components/Button.js",
    "file"
  ],
  [
    "src/components/element.js",
    "file/src/components/Element.js.html",
    "src/components/Element.js",
    "file"
  ],
  [
    "src/components/element.js~boxproperties",
    "typedef/index.html#static-typedef-BoxProperties",
    "src/components/Element.js~BoxProperties",
    "typedef"
  ],
  [
    "src/components/expander.js",
    "file/src/components/Expander.js.html",
    "src/components/Expander.js",
    "file"
  ],
  [
    "src/components/icon.js",
    "file/src/components/Icon.js.html",
    "src/components/Icon.js",
    "file"
  ],
  [
    "src/components/iconview.js",
    "file/src/components/IconView.js.html",
    "src/components/IconView.js",
    "file"
  ],
  [
    "src/components/iframe.js",
    "file/src/components/Iframe.js.html",
    "src/components/Iframe.js",
    "file"
  ],
  [
    "src/components/image.js",
    "file/src/components/Image.js.html",
    "src/components/Image.js",
    "file"
  ],
  [
    "src/components/label.js",
    "file/src/components/Label.js.html",
    "src/components/Label.js",
    "file"
  ],
  [
    "src/components/listview.js",
    "file/src/components/ListView.js.html",
    "src/components/ListView.js",
    "file"
  ],
  [
    "src/components/menu.js",
    "file/src/components/Menu.js.html",
    "src/components/Menu.js",
    "file"
  ],
  [
    "src/components/menu.js~menuitems",
    "typedef/index.html#static-typedef-MenuItems",
    "src/components/Menu.js~MenuItems",
    "typedef"
  ],
  [
    "src/components/menubar.js",
    "file/src/components/Menubar.js.html",
    "src/components/Menubar.js",
    "file"
  ],
  [
    "src/components/panes.js",
    "file/src/components/Panes.js.html",
    "src/components/Panes.js",
    "file"
  ],
  [
    "src/components/progressbar.js",
    "file/src/components/Progressbar.js.html",
    "src/components/Progressbar.js",
    "file"
  ],
  [
    "src/components/rangefield.js",
    "file/src/components/RangeField.js.html",
    "src/components/RangeField.js",
    "file"
  ],
  [
    "src/components/selectfield.js",
    "file/src/components/SelectField.js.html",
    "src/components/SelectField.js",
    "file"
  ],
  [
    "src/components/statusbar.js",
    "file/src/components/Statusbar.js.html",
    "src/components/Statusbar.js",
    "file"
  ],
  [
    "src/components/tabs.js",
    "file/src/components/Tabs.js.html",
    "src/components/Tabs.js",
    "file"
  ],
  [
    "src/components/textfield.js",
    "file/src/components/TextField.js.html",
    "src/components/TextField.js",
    "file"
  ],
  [
    "src/components/textareafield.js",
    "file/src/components/TextareaField.js.html",
    "src/components/TextareaField.js",
    "file"
  ],
  [
    "src/components/togglefield.js",
    "file/src/components/ToggleField.js.html",
    "src/components/ToggleField.js",
    "file"
  ],
  [
    "src/components/toolbar.js",
    "file/src/components/Toolbar.js.html",
    "src/components/Toolbar.js",
    "file"
  ],
  [
    "src/components/video.js",
    "file/src/components/Video.js.html",
    "src/components/Video.js",
    "file"
  ],
  [
    "src/contextmenu.js",
    "file/src/contextmenu.js.html",
    "src/contextmenu.js",
    "file"
  ],
  [
    "src/contextmenu.js~contextmenu#hide",
    "class/src/contextmenu.js~ContextMenu.html#instance-method-hide",
    "src/contextmenu.js~ContextMenu#hide",
    "method"
  ],
  [
    "src/contextmenu.js~contextmenu#init",
    "class/src/contextmenu.js~ContextMenu.html#instance-method-init",
    "src/contextmenu.js~ContextMenu#init",
    "method"
  ],
  [
    "src/contextmenu.js~contextmenu#show",
    "class/src/contextmenu.js~ContextMenu.html#instance-method-show",
    "src/contextmenu.js~ContextMenu#show",
    "method"
  ],
  [
    "src/element.js",
    "file/src/element.js.html",
    "src/element.js",
    "file"
  ],
  [
    "src/provider.js",
    "file/src/provider.js.html",
    "src/provider.js",
    "file"
  ],
  [
    "src/umd.js",
    "file/src/umd.js.html",
    "src/umd.js",
    "file"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]