window.esdocSearchIndex = [
  [
    "@osjs/dialogs/src/dialogs/alert.js~alertdialog",
    "class/src/dialogs/alert.js~AlertDialog.html",
    "<span>AlertDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/alert.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/choice.js~choicedialog",
    "class/src/dialogs/choice.js~ChoiceDialog.html",
    "<span>ChoiceDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/choice.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/color.js~colordialog",
    "class/src/dialogs/color.js~ColorDialog.html",
    "<span>ColorDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/color.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/confirm.js~confirmdialog",
    "class/src/dialogs/confirm.js~ConfirmDialog.html",
    "<span>ConfirmDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/confirm.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/default-application.js~defaultapplicationdialog",
    "class/src/dialogs/default-application.js~DefaultApplicationDialog.html",
    "<span>DefaultApplicationDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/default-application.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialog.js~dialog",
    "class/src/dialog.js~Dialog.html",
    "<span>Dialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialog.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/file.js~filedialog",
    "class/src/dialogs/file.js~FileDialog.html",
    "<span>FileDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/file.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/font.js~fontdialog",
    "class/src/dialogs/font.js~FontDialog.html",
    "<span>FontDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/font.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/progress.js~progressdialog",
    "class/src/dialogs/progress.js~ProgressDialog.html",
    "<span>ProgressDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/progress.js</span>",
    "class"
  ],
  [
    "@osjs/dialogs/src/dialogs/prompt.js~promptdialog",
    "class/src/dialogs/prompt.js~PromptDialog.html",
    "<span>PromptDialog</span> <span class=\"search-result-import-path\">@osjs/dialogs/src/dialogs/prompt.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/dialog.js",
    "file/src/dialog.js.html",
    "src/dialog.js",
    "file"
  ],
  [
    "src/dialog.js~dialog#constructor",
    "class/src/dialog.js~Dialog.html#instance-constructor-constructor",
    "src/dialog.js~Dialog#constructor",
    "method"
  ],
  [
    "src/dialog.js~dialog#createbuttons",
    "class/src/dialog.js~Dialog.html#instance-method-createButtons",
    "src/dialog.js~Dialog#createButtons",
    "method"
  ],
  [
    "src/dialog.js~dialog#createview",
    "class/src/dialog.js~Dialog.html#instance-method-createView",
    "src/dialog.js~Dialog#createView",
    "method"
  ],
  [
    "src/dialog.js~dialog#destroy",
    "class/src/dialog.js~Dialog.html#instance-method-destroy",
    "src/dialog.js~Dialog#destroy",
    "method"
  ],
  [
    "src/dialog.js~dialog#emitcallback",
    "class/src/dialog.js~Dialog.html#instance-method-emitCallback",
    "src/dialog.js~Dialog#emitCallback",
    "method"
  ],
  [
    "src/dialog.js~dialog#getnegativebutton",
    "class/src/dialog.js~Dialog.html#instance-method-getNegativeButton",
    "src/dialog.js~Dialog#getNegativeButton",
    "method"
  ],
  [
    "src/dialog.js~dialog#getpositivebutton",
    "class/src/dialog.js~Dialog.html#instance-method-getPositiveButton",
    "src/dialog.js~Dialog#getPositiveButton",
    "method"
  ],
  [
    "src/dialog.js~dialog#getvalue",
    "class/src/dialog.js~Dialog.html#instance-method-getValue",
    "src/dialog.js~Dialog#getValue",
    "method"
  ],
  [
    "src/dialog.js~dialog#playsound",
    "class/src/dialog.js~Dialog.html#instance-method-playSound",
    "src/dialog.js~Dialog#playSound",
    "method"
  ],
  [
    "src/dialog.js~dialog#render",
    "class/src/dialog.js~Dialog.html#instance-method-render",
    "src/dialog.js~Dialog#render",
    "method"
  ],
  [
    "src/dialogs/alert.js",
    "file/src/dialogs/alert.js.html",
    "src/dialogs/alert.js",
    "file"
  ],
  [
    "src/dialogs/alert.js~alertdialog#constructor",
    "class/src/dialogs/alert.js~AlertDialog.html#instance-constructor-constructor",
    "src/dialogs/alert.js~AlertDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/choice.js",
    "file/src/dialogs/choice.js.html",
    "src/dialogs/choice.js",
    "file"
  ],
  [
    "src/dialogs/choice.js~choicedialog#constructor",
    "class/src/dialogs/choice.js~ChoiceDialog.html#instance-constructor-constructor",
    "src/dialogs/choice.js~ChoiceDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/color.js",
    "file/src/dialogs/color.js.html",
    "src/dialogs/color.js",
    "file"
  ],
  [
    "src/dialogs/color.js~colordialog#constructor",
    "class/src/dialogs/color.js~ColorDialog.html#instance-constructor-constructor",
    "src/dialogs/color.js~ColorDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/confirm.js",
    "file/src/dialogs/confirm.js.html",
    "src/dialogs/confirm.js",
    "file"
  ],
  [
    "src/dialogs/confirm.js~confirmdialog#constructor",
    "class/src/dialogs/confirm.js~ConfirmDialog.html#instance-constructor-constructor",
    "src/dialogs/confirm.js~ConfirmDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/default-application.js",
    "file/src/dialogs/default-application.js.html",
    "src/dialogs/default-application.js",
    "file"
  ],
  [
    "src/dialogs/default-application.js~defaultapplicationdialog#constructor",
    "class/src/dialogs/default-application.js~DefaultApplicationDialog.html#instance-constructor-constructor",
    "src/dialogs/default-application.js~DefaultApplicationDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/file.js",
    "file/src/dialogs/file.js.html",
    "src/dialogs/file.js",
    "file"
  ],
  [
    "src/dialogs/file.js~filedialog#constructor",
    "class/src/dialogs/file.js~FileDialog.html#instance-constructor-constructor",
    "src/dialogs/file.js~FileDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/font.js",
    "file/src/dialogs/font.js.html",
    "src/dialogs/font.js",
    "file"
  ],
  [
    "src/dialogs/font.js~fontdialog#constructor",
    "class/src/dialogs/font.js~FontDialog.html#instance-constructor-constructor",
    "src/dialogs/font.js~FontDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/progress.js",
    "file/src/dialogs/progress.js.html",
    "src/dialogs/progress.js",
    "file"
  ],
  [
    "src/dialogs/progress.js~progressdialog#constructor",
    "class/src/dialogs/progress.js~ProgressDialog.html#instance-constructor-constructor",
    "src/dialogs/progress.js~ProgressDialog#constructor",
    "method"
  ],
  [
    "src/dialogs/progress.js~progressdialog#setprogress",
    "class/src/dialogs/progress.js~ProgressDialog.html#instance-method-setProgress",
    "src/dialogs/progress.js~ProgressDialog#setProgress",
    "method"
  ],
  [
    "src/dialogs/progress.js~progressdialog#setstatus",
    "class/src/dialogs/progress.js~ProgressDialog.html#instance-method-setStatus",
    "src/dialogs/progress.js~ProgressDialog#setStatus",
    "method"
  ],
  [
    "src/dialogs/prompt.js",
    "file/src/dialogs/prompt.js.html",
    "src/dialogs/prompt.js",
    "file"
  ],
  [
    "src/dialogs/prompt.js~promptdialog#constructor",
    "class/src/dialogs/prompt.js~PromptDialog.html#instance-constructor-constructor",
    "src/dialogs/prompt.js~PromptDialog#constructor",
    "method"
  ],
  [
    "src/provider.js",
    "file/src/provider.js.html",
    "src/provider.js",
    "file"
  ]
]